### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FreshKhalifa347**

### CODE REVIEW

**Review by Karma6353 — APPROVED** [review]

**Review by Carsonmarvel1 — CHANGES_REQUESTED** [review]
Return

**Review by NostalgicGareth — APPROVED** [review]
approve

**Review by drvsinan — APPROVED** [review]

**Comment by drvsinan** [comment]
Öpen

**Comment by drvsinan** [comment]
> README.md

**Review by NostalgicGareth — APPROVED** [review]

**Review by ZxSix666 — APPROVED** [review]

**Comment by mazr711001** [comment]
Can proses

**Comment by mazr711001** [comment]
Can proses

**Review by drvsinan — APPROVED** [review]

**Review by NostalgicGareth — APPROVED** [review]
- [ ]

**Review by drvsinan — APPROVED** [review]

**Review by NostalgicGareth — APPROVED** [review]
- [ ]

**Review by slumericanB — APPROVED** [review]

**Review by NostalgicGareth — APPROVED** [review]
- [ ]

**Review by slumericanB — APPROVED** [review]
(y)

**Pull request closed without merging**
