### PR TITLE
Update bootstrap.css

### PR DESCRIPTION
**Pull request by Wrathchyld**
Localhost 4242

### CODE REVIEW

**Comment by Newman1515** [comment]
From 79b4351ed4e3ec85ca363fbb2121e93641a562c2 Mon Sep 17 00:00:00 2001
From: Jerry Robertson <100456128+Wrathchyld@users.noreply.github.com>
Date: Sat, 16 Apr 2022 12:42:09 -0400
Subject: [PATCH] Update bootstrap.css

Localhost 4242
---
 css/bootstrap.css | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/css/bootstrap.css b/css/bootstrap.css
index 3054b9a..0598131 100644
--- a/css/bootstrap.css
+++ b/css/bootstrap.css
@@ -9632,4 +9632,4 @@
  
  .pagination .page-link:hover {
    text-decoration: none;
- }
\ No newline at end of file
+ }Jerry Robertson

**Comment by Newman1515** [comment]
diff --git a/css/bootstrap.css b/css/bootstrap.css
index 3054b9a..0598131 100644
--- a/css/bootstrap.css
+++ b/css/bootstrap.css
@@ -9632,4 +9632,4 @@
  
  .pagination .page-link:hover {
    text-decoration: none;
- }
\ No newline at end of file
+ }Francisco A Rivera

**Review by Newman1515 — APPROVED** [review]

**Review by Newman1515 — APPROVED** [review]

**Review by Newman1515 — APPROVED** [review]
Ok approve

**Comment by Ash1818** [comment]
Tracking you

**Comment by Mdk2022** [comment]
Hello

**Comment by Mdk2022** [comment]
Hello can verify it

**Comment by Newman1515** [comment]
Hello

**Review by Newman1515 — APPROVED** [review]
Ok

**Comment by 122wr** [comment]
Vai dar certo

**Comment by 122wr** [comment]
> Localhost 4242

Wrathchyld:patch-1

**Comment by sasanpc85** [comment]
yes

Sent from Yahoo Mail on Android 
 
  On Fri, May 13, 2022 at 11:39, ***@***.***> wrote:   


Tracking you

**Pull request closed without merging**
