### PR TITLE
Added logic to show the account nonce on lookup

### PR DESCRIPTION
**Pull request by 409H**
Closes issue https://github.com/etherscan/ethvalidate/issues/9

On address lookup, it will show the account nonce for each network.
image

### CODE REVIEW

**Comment by DBLGT147** [comment]
https://etherscan.github.io/ethvalidate/address?a=0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be

**Comment by Enigmatic331** [comment]
Hi @409H - Thanks for the PR and sorry for the late reply.

Generally I think it's fine, though could we have the label reflect "Current Nonce"? Think that could be clearer in case it is misunderstood that the nonce is reflecting the tx's nonce.

Feel free to let me know what you think.

**Comment by 409H** [comment]
@Enigmatic331 I updated the label, good idea.

**Review by soulfulAdam — APPROVED** [review]

**Review by soulfulAdam — COMMENTED** [review]
Request changes

**Review by Scheusal13 — COMMENTED** [review]
Ok

**Review by sara554-beep — APPROVED** [review]
Fin

**Pull request merged**
